version: '2.3'

volumes:
  psql.data:
    driver: local
  opennms.data:
    driver: local

networks:
  opennms.net:
    driver: bridge

services:
  database:
    container_name: opennms.psql
    image: postgres:9.6
    env_file:
      - .postgres.env
    networks:
      - opennms.net
    volumes:
      - psql.data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"

  opennms:
    container_name: opennms.build.env
    image: opennms/build-env:latest
    init: true
    env_file:
      - .opennms.env
      - .postgres.env
    networks:
      - opennms.net
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ../target/opennms-22.0.0-SNAPSHOT:/opt/opennms
      - ./etc-overlay:/opt/opennms-etc-overlay
    entrypoint: [ "/docker-entrypoint.sh" ]
    command: ["-s"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp"]
      interval: 1m
      timeout: 5s
      retries: 3
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616"
      - "162:162/udp"
